// Reuse reviewed identity/search labels; never manufacture missing translations.
import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=new URL('../',import.meta.url);
const aliases=JSON.parse(await readFile(new URL('config/player-aliases.json',root),'utf8'));
const data=JSON.parse(await readFile(new URL('app/data/guess-players.json',root),'utf8'));
const byId=new Map(data.players.map(player=>[player.id,player]));
const han=/\p{Script=Han}/u;
const names=Object.fromEntries(Object.entries(aliases.players).map(([id,entry])=>{
  const player=byId.get(id);
  const englishName=player&&!han.test(player.name)?player.name:(entry.aliases||[]).find(name=>/^[A-Z][\p{Script=Latin}.'’ -]+$/u.test(name)&&name.includes(' '))||null;
  return [id,{chineseName:entry.chineseName,englishName,aliases:entry.aliases||[]}];
}));
const out=new URL('app/player-name-data.mjs',root);
await writeFile(out,'// Generated by scripts/38_build_player_name_data.mjs from reviewed config/player-aliases.json.\n// Labels are common or editorial translations, not claims of unique official names.\nexport const PLAYER_NAMES = '+JSON.stringify(names,null,2)+';\n');
console.log(`Saved ${Object.keys(names).length} reviewed player labels to ${fileURLToPath(out)}`);
